-- JOIN, ON, 서브쿼리 사용
SELECT f.ID as ID, n.FISH_NAME as FISH_NAME, f.LENGTH as LENGTH
FROM FISH_INFO f
INNER JOIN FISH_NAME_INFO n
ON f.FISH_TYPE = n.FISH_TYPE
WHERE (f.FISH_TYPE, f.LENGTH) IN (SELECT FISH_TYPE, MAX(LENGTH) FROM FISH_INFO GROUP BY FISH_TYPE)
ORDER BY ID
